version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: Root
            POSTGRES_PASSWORD: Root@1234
            POSTGRES_DB: crm
        ports:
            - "5432:5432"
        networks:
            - pg-net

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: vft.devs@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 8DHDDgeOYxt8wCk
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - pg-net

networks:
    pg-net:
