version: "3.8"

services:
    redis-stack:
        image: redis/redis-stack:latest
        container_name: redis-stack-2
        ports:
            - "8001:8001"
        networks:
            - redis-net

    redis-stack-server:
        image: redis/redis-stack-server:latest
        container_name: redis-stack-server-2
        ports:
            - "6379:6379"
        networks:
            - redis-net

networks:
    redis-net:
